# Generated by Django 4.2 on 2026-04-05 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December'), ('S1', 'Semester 1'), ('S2', 'Semester 2')], max_length=3)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial Payment'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bills', to='academic.academicyear')),
                ('bill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bills', to='payments.billtype')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bills', to='academic.class')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Bill',
                'verbose_name_plural': 'Student Bills',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMESTER', 'Semester'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('start_month', models.IntegerField(default=1)),
                ('number_of_periods', models.IntegerField(default=12)),
                ('days_before_due', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('bill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='payments.billtype')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('E_WALLET', 'E-Wallet (Midtrans)'), ('DEBIT_CARD', 'Debit Card')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SUCCESS', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('student_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='payments.studentbill')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='studentbill',
            index=models.Index(fields=['student', 'status'], name='payments_st_student_f9f8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbill',
            index=models.Index(fields=['due_date', 'status'], name='payments_st_due_dat_8ff9f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbill',
            unique_together={('student', 'bill_type', 'academic_year', 'period')},
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['student_bill', 'payment_date'], name='payments_pa_student_a9e780_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['status', 'payment_date'], name='payments_pa_status_faf0fd_idx'),
        ),
    ]
