# Generated by Django 4.2 on 2026-04-05 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1)),
                ('assignment_average', models.FloatField(default=0)),
                ('exam_average', models.FloatField(default=0)),
                ('attendance_score', models.FloatField(default=0)),
                ('practical_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('letter_grade', models.CharField(blank=True, choices=[('A', 'A (90-100)'), ('B', 'B (80-89)'), ('C', 'C (70-79)'), ('D', 'D (60-69)'), ('E', 'E (< 60)')], max_length=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_books', to='academic.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_books', to='academic.class')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_books', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Grade Book',
                'verbose_name_plural': 'Grade Books',
                'ordering': ['-academic_year', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1)),
                ('gpa', models.FloatField(default=0)),
                ('total_credits', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_cards/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('principal_notes', models.TextField(blank=True, null=True)),
                ('homeroom_teacher_notes', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academic.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academic.class')),
                ('published_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_report_cards', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('student', 'class_obj', 'academic_year', 'semester')},
            },
        ),
        migrations.AddIndex(
            model_name='gradebook',
            index=models.Index(fields=['student', 'academic_year'], name='grades_grad_student_eb2a02_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebook',
            index=models.Index(fields=['class_obj', 'semester'], name='grades_grad_class_o_610422_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradebook',
            unique_together={('student', 'subject', 'class_obj', 'academic_year', 'semester')},
        ),
    ]
