# Generated by Django 4.2 on 2026-04-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='deletion_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='deletion_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
