# Generated by Django 4.2 on 2026-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_add_options_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='violations_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='options_images',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
