# Generated by Django 4.2 on 2026-04-06 22:30

from django.db import migrations, models


def convert_attendance_status(apps, schema_editor):
    """Convert LATE and EXCUSE to PRESENT"""
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')

    # Convert LATE to PRESENT
    late_records = AttendanceRecord.objects.filter(status='LATE')
    late_count = late_records.count()
    late_records.update(status='PRESENT')

    # Convert EXCUSE to PRESENT
    excuse_records = AttendanceRecord.objects.filter(status='EXCUSE')
    excuse_count = excuse_records.count()
    excuse_records.update(status='PRESENT')

    if late_count > 0:
        print(f"\n[OK] Converted {late_count} LATE records to PRESENT")
    if excuse_count > 0:
        print(f"[OK] Converted {excuse_count} EXCUSE records to PRESENT")
    if late_count == 0 and excuse_count == 0:
        print("\n[INFO] No LATE or EXCUSE records found to convert")


def reverse_convert_attendance_status(apps, schema_editor):
    """Reverse migration - cannot restore original status"""
    print("\n[WARNING] Cannot reverse conversion - original status data was lost\n")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_and_more'),
    ]

    operations = [
        # First: Convert existing data BEFORE changing field choices
        migrations.RunPython(convert_attendance_status, reverse_convert_attendance_status),

        # Then: Change field choices from 5 to 3 options
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SICK', 'Sick')], default='PRESENT', max_length=20),
        ),
    ]
