# Generated by Django 4.2 on 2026-04-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0002_initial'),
        ('attendance', '0003_change_attendance_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='attendance__class_o_41c4bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesession',
            name='attendance__class_o_0c840f_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesession',
            name='attendance__teacher_d7ed71_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='class_subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.classsubjectteacher'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SICK', 'Sick'), ('PERMISSION', 'Permission')], default='PRESENT', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'attendance_session', 'attendance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('class_subject_teacher', 'session_date')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance_session', 'attendance_date'], name='attendance__attenda_0efdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['class_subject_teacher', 'session_date'], name='attendance__class_s_a7da84_idx'),
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='teacher',
        ),
    ]
