# Generated by Django 4.2 on 2026-04-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancerecord_attendance__class_o_41c4bf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Current valid QR token for this session', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='qr_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the current QR token expires', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='qr_token_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the current QR token was generated', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_type',
            field=models.CharField(choices=[('LURING', 'Tatap Muka (In-Person)'), ('DARING', 'Pembelajaran Daring (Online)')], default='LURING', help_text='LURING: In-person with QR code scanning, DARING: Online with student submission', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['session_type'], name='attendance__session_70d121_idx'),
        ),
    ]
